### ISSUE TITLE
请问您的主题能支持disqus吗？

### ISSUE THREAD

**Issue by yyz20002008** [jangdelong/hexo-theme-xups#10]
请问您的主题能支持disqus吗？
现在网上加disqus的经验多是next 主题
您的主题很简洁 很想用 就是没太搞清楚如果要加disqus不用gittak怎么改js

**Comment by jangdelong** [comment]
<img width="651" alt="image" src="https://user-images.githubusercontent.com/5547151/64089844-a3d72180-cd7a-11e9-95f3-b86f2c7ff8a9.png">

可以直接改造comment.ejs模块
