### ISSUE TITLE
博客页面问题？

### ISSUE THREAD

**Issue by wuxianqiang** [jangdelong/hexo-theme-xups#4]
您好！我在我博客的source目录下建立了关于页面和留言页面，但是还是只能显示您默认的页面，我要如何操作才能修改显示自己的内容？

**Comment by jangdelong** [comment]
![image](https://user-images.githubusercontent.com/5547151/31862472-e94f9498-b703-11e7-872f-9ce4168a9ae0.png) ，要在放置文章 md 文件的目录，而不是 theme 主题的目录哦。

**Comment by wuxianqiang** [comment]
好的，谢谢
