### ISSUE TITLE
建议增加新功能

### ISSUE THREAD

**Issue by whg517** [jangdelong/hexo-theme-xups#5]
您好，看到你的博客，感觉布局和风格比较清爽，用着挺好。但是我也不太会前端技术，所以提出几个我认为还不错的功能，希望您能够采纳。
1. 添加在窗口最大后的右侧滚动条。方便博文太长的快速调整浏览位置。当然如果能有个固定显示目录的区域，通过点击标题快速跳转就好了。
2. 添加点击图片弹窗，可以缩放。方便看清截图。或者点击图片在新窗口打开图片。

**Comment by jangdelong** [comment]
嗯，谢谢建议……
